name: GCP Build and Deploy

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      dockerfile_path:
        required: false
        type: string
        default: "./Dockerfile"
      artifact_registry_region:
        required: true
        type: string
      artifact_registry_repository:
        required: true
        type: string
      cloudrun_service:
        required: true
        type: string
      cloudrun_region:
        required: true
        type: string
    secrets:
      gcp_project_id:
        required: true
      gcp_workload_identity_provider:
        required: true
      gcp_service_account:
        required: true

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Debug secrets
        run: |
          echo "project_id: ${{ secrets.gcp_project_id }}"
          echo "workload_provider: ${{ secrets.gcp_workload_identity_provider }}"
          echo "service_account: ${{ secrets.gcp_service_account }}"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          workload_identity_provider: ${{ secrets.gcp_workload_identity_provider }}
          service_account: ${{ secrets.gcp_service_account }}

      - name: Login to Artifact Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.artifact_registry_region }}-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ inputs.dockerfile_path }}
          push: true
          tags: |
            ${{ inputs.artifact_registry_region }}-docker.pkg.dev/${{ secrets.gcp_project_id }}/${{ inputs.artifact_registry_repository }}/${{ inputs.image_name }}:${{ github.sha }}
            ${{ inputs.artifact_registry_region }}-docker.pkg.dev/${{ secrets.gcp_project_id }}/${{ inputs.artifact_registry_repository }}/${{ inputs.image_name }}:latest

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ inputs.cloudrun_service }}
          region: ${{ inputs.cloudrun_region }}
          image: ${{ inputs.artifact_registry_region }}-docker.pkg.dev/${{ secrets.gcp_project_id }}/${{ inputs.artifact_registry_repository }}/${{ inputs.image_name }}:${{ github.sha }}
